### ISSUE TITLE
Mislabelled file path and lack of example

### ISSUE THREAD

**Issue by pajamaw** [learn-co-curriculum/oo-student-scraper#14]
In the "before you begin" section it says that in order to do this we'll be using a copy of the student site found in oo-student-scraper/fixtures/student-site but this directory doesn't exist. The closest thing i found to it is oo-student-scraper/vcr/fixtures/index_page.yml. Also after the request to run jekyll serve there is room for the example of what running that specific command should output, and there's no example.

**Comment by deniznida** [comment]
@pajamaw this should be fixed now

**Comment by pajamaw** [comment]
beautiful thanks!
-PJ

**Comment by pajamaw** [comment]
the filepath still seems to be mislabelled. when i forked the lab over 
there was no oo-student-scraper/fixtures/student-site directory

**Comment by deniznida** [comment]
@pajamaw you need to update your fork, to do so go to this link https://help.github.com/articles/syncing-a-fork/
