### ISSUE TITLE
test expects scrape_index_page method to return absolute URLs

### ISSUE THREAD

**Issue by HarlemSquirrel** [learn-co-curriculum/oo-student-scraper#17]
So when I scrape the index.html page I get relative URLs like `students/diane-vu.html` but `rspec/scraper_spec.rb` expects `http://127.0.0.1:4000/students/diane-vu.html`

**Comment by HarlemSquirrel** [comment]
I just added a commit to my fork that changes the URLs in the spec to be relative and now that test passes.

**Comment by AnnJohn** [comment]
thanks for raising this @HarlemSquirrel. We'll look into this soon.

**Comment by vicfriedman** [comment]
hey @HarlemSquirrel,

Your scraper method that scrapes the index URL actually needs to add the full URL path to the scraped relative path. The test is actually testing the correct functionality. I'm going to close the issue. Let me know if you have any questions
