### ISSUE TITLE
Capital letters throwing off test

### ISSUE THREAD

**Issue by tjnz** [learn-co-curriculum/oo-student-scraper#21]
Capital letters in the students (Minh Nguyen and Duc Pham) urls dont match the src urls provided in the index.html fixture.  Both students profile pages should be named with lower case letters and their sources in the index.html should match.  Otherwise you get a 404 and bin/run will break.

**Comment by AnnJohn** [comment]
thanks for raising this. We'll fix this as soon as we can.
