### ISSUE TITLE
please review my hack of the rspec file, let me know if I am off track please

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/oo-student-scraper#26]
I found that the URL showing on my local browser was this: 
http://127.0.0.1:4000/fixtures/student-site/

The test files where set to look for this: 
http://127.0.0.1:4000/

So I had to hack the scraper_spec.rb file in the following places to get tests to pass: 

  let!(:student_index_array) {[{:name=>"Joe Burgess", :location=>"New York, NY", :profile_url=>"http://127.0.0.1:4000/**fixtures/student-site**/students/joe-burgess.html"},
                               {:name=>"Mathieu Balez", :location=>"New York, NY", :profile_url=>"http://127.0.0.1:4000/**fixtures/student-site**/students/mathieu-balez.html"},
                               {:name=>"Diane Vu", :location=>"New York, NY", :profile_url=>"http://127.0.0.1:4000/**fixtures/student-site**/students/diane-vu.html"}]}

also here:   
  describe "#scrape_index_page" do 
    it "is a class method that scrapes the student index page and a returns an array of hashes in which each hash represents one student" do 
      index_url = "http://127.0.0.1:4000/**fixtures/student-site**/"
      scraped_students = Scraper.scrape_index_page(index_url)
      expect(scraped_students).to be_a(Array)
      expect(scraped_students.first).to have_key(:location)
      expect(scraped_students.first).to have_key(:name)
      expect(scraped_students).to include(student_index_array[0], student_index_array[1], student_index_array[2])
    end
  end

**Comment by pletcher** [comment]
This seems okay, but the additional URL paths shouldn't be strictly necessary -- feel free to compare your solution with what's in the solution branch: https://github.com/learn-co-curriculum/oo-student-scraper/tree/solution/lib
