### ISSUE TITLE
after starting  'jekyll' the student site is not showing

### ISSUE THREAD

**Issue by deniznida** [learn-co-curriculum/oo-student-scraper#30]
after starting  'jekyll' I see this in my browser

<img width="1271" alt="screen shot 2016-04-12 at 10 25 50 pm" src="https://cloud.githubusercontent.com/assets/9004428/14481111/bf58b6a0-00fd-11e6-86ef-8a2ca11c799a.png">

I had to enter manually `http://127.0.0.1:4000/fixtures/student-site/` to see the student site. A student had the same issue.

**Comment by aturkewi** [comment]
Test passes by if you change the following lines in the spec file: 
# line 26
`index_url = "http://127.0.0.1:4000/fixtures/student-site/"`

#line 37
`profile_url = "http://127.0.0.1:4000/fixtures/student-site/students/joe-burgess.html"`
  
  #line 44
  `profile_url = "http://127.0.0.1:4000/fixtures/student-site/students/david-kim.html"`

**Comment by aturkewi** [comment]
@aturkewi

Taggin' myself so I fix this post-shift

**Comment by PeterBell** [comment]
fixed by #31
