### ISSUE TITLE
Run jekyll server using Nitrous.io

### ISSUE THREAD

**Issue by mottigottlieb** [learn-co-curriculum/oo-student-scraper#35]
Step 1.
Paste in console: "python -m SimpleHTTPServer 3000"

Step 2.
	Select Preview > Port 3000 (Default)

Step 3.
	Open a new Shell and type "jekyll server"
	
Step 4.
	Open a new Shell for testing
	
link to Nitrous doc:
https://community.nitrous.io/docs/preview-a-static-html-page

**Comment by AnnJohn** [comment]
hi @mottigottlieb thanks for these steps. We're sunsetting Nitrous and are now using an IDE that we developed in-house so a lot of the Nitrous problems should no longer be issues.
