### ISSUE TITLE
url in rspec doesn't match the actual url.  

### ISSUE THREAD

**Issue by iandevivi** [learn-co-curriculum/oo-student-scraper#47]
rspec is looking for "http://127.0.0.1:4000/"

The url for the page we're scraping is "http://127.0.0.1:4000/fixtures/student-site/".  This was a bit confusing when testing and running the CLI.

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the _content_ of this lesson. If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by aturkewi** [comment]
Thanks for posting this @iandevivi 

I've actually updated the lab so it just grabs the local file and we don't have to worry about what URL a server is running on. Please keep raising issues if you see anything else, and thanks for helping us make Learn better!
