### ISSUE TITLE
Conceptual disagreement?

### ISSUE THREAD

**Issue by thekayness** [learn-co-curriculum/oo-student-scraper#51]
I feel like the #SCRAPE_INDEX_PAGE method description doesn't necessarily jive with what the rspec test expects from us.  From reading the description it feels conceptually like we can get the values for our hash keys just from what we've scraped from the page.  We don't really get a hint that we might need to modify those values (namely for the : profile_url value).  The scraped data in this case does not match the test output; we need to add additional directions to a specific local file path for the test to pass, rather than the actual url value that we can scrape from the index.html page.  We are not given any explanation as to why this output needs to be different, so those more curious are left to wonder why for a symbol named profile_url we need to output a local file path instead.

Just my 2 cents.

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by thekayness** [comment]
I don't think this is a bug per se, just how the information we're presented in the student scraper readme seems fundamentally different than what the test expects.  If we look at the index.html, what we get back when we look for what appears to be a profile url is <a href="students/jennifer-anton.html">.  The test expects "./fixtures/student-site/students/jennifer-anton.html".

Am I making any sense about where I got confused?

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestions. We updated the assignment README and specs to provide a more accurate description of the Scraper.scrape_index_page method input and output.

If you still feel that there is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

As always, thanks for contributing! 💙
