### ISSUE TITLE
Errors in filenames for student profile pages

### ISSUE THREAD

**Issue by lair001** [learn-co-curriculum/oo-student-scraper#52]
In the students folder, Jelson-Rodriguez.html needs to be renamed to jelson-rodriguez.html and Minh-Nguyen.html needs to be renamed to minh-nguyen.html for bin/run to work properly after the lab is complete.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the correction. We updated the two filenames.

As always, thanks for contributing! 💙
