### ISSUE TITLE
#scrape_profile_page test is too general 

### ISSUE THREAD

**Issue by dannyd4315** [learn-co-curriculum/oo-student-scraper#6]
The tests in this lab are too general, specifically for #scrape_profile_page. The test passes as long as a hash is returned, irrespective of what is contained within the hash.

Also with regards to the solution. If you call the child elements using [0] element and the profile page does not have a twitter icon (for example), then the twitter key will have a value of the next link that it does have. For example a linkedin link. So the keys will have incorrect values in accordance with the name of the key.

**Comment by sammarcus** [comment]
thanks @dannyd4315 !

**Comment by sammarcus** [comment]
thanks @dannyd4315 ! (cc @AnnJohn )

**Comment by AnnJohn** [comment]
thanks @dannyd4315!
