### ISSUE TITLE
Program will not run

### ISSUE THREAD

**Issue by jennianelson** [learn-co-curriculum/oo-student-scraper#63]
After passing all tests for this lab, I attempted to run the program but received the following error.  I have not changed command_line_interface.rb and even compared it to the master branch just in case. 
![screen shot 2017-09-04 at 8 55 20 pm](https://user-images.githubusercontent.com/26926371/30041927-6601f38a-91b3-11e7-8550-3d8c9c2a1c0e.png)

From what I can tell, the problem is that #add_attributes_to_students expects there to be a profile-url in each instance of a student.  Each student is only initialized with a name and location. There is an attribute accessor for profile_url, but it is never used in the class and returns nil.   Here are lines 20-25 from lib/command_line_interface.rb
`def add_attributes_to_students
    Student.all.each do |student|
      attributes = Scraper.scrape_profile_page(BASE_PATH + student.profile_url)
      student.add_student_attributes(attributes)
    end
  end`

**Comment by curiositypaths** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE) and a link to your repository clone, I'd be happy to take a second look!

As always, thanks for contributing! 💙
