### ISSUE TITLE
Image of "Desired Output" for #scrape_index_page does not match test specs

### ISSUE THREAD

**Issue by lwebber** [learn-co-curriculum/oo-student-scraper#64]
Change image of "Desired Output" for #scrape_index_page to match test specs, specifically the file path expected.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestions. We updated the assignment README and specs to provide a more accurate description of the `Scraper.scrape_index_page` method input and output.

If you still feel that there is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

As always, thanks for contributing! 💙
