### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ode-to-the-code** [learn-co-curriculum/oo-student-scraper#66]
the word 'nokogiri' should be capitalized, but is lower case throughout the lab text

**Comment by DanielSeehausen** [comment]
Thank you for spotting this issue and providing feedback @ode-to-the-code!

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
