### ISSUE TITLE
Typo in #initialize method paragraph...word achieve

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/oo-student-scraper#72]
Correct spelling is achieve (see below).
The #initialize method should take in an argument of a hash and use metaprogramming to assign the newly created student attributes and values in accordance with the key/value pairs of the hash. Use the #send method to acheive this.

**Comment by sgharms** [comment]
Thanks! Fixed!

**Comment by ccklight** [comment]
Hi Steven,

Are my contributions - “raise an issue” kept in my github profile? ? I do
not see it in files.

 I’m only 35% in my curriculum so I can only address minor typos. FI is
excellent so  there are no code problems ( and if there were I wouldn’t be
able yet to detect them in rspec etc).

Still, I want to continue showing my track record of activity,
participation in my community, and teamwork in my github. If it’s not in
Github, how can I do this ?

Thanks for your response.
