### ISSUE TITLE
Create From Collection Issue

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/oo-student-scraper#73]
Hey, so in the spec for the create_from_collection method in the Student class, it says the method will use the Scraper class: 
`.create_from_collection
    uses the Scraper class to create new students with the correct name and location.`

But the solution does not use the Scraper class at all. 
`def self.create_from_collection(students_array)
    students_array.each do |student_hash|
      Student.new(student_hash)
    end
  end`

**Comment by sgharms** [comment]
@helloamandamurphy Thanks for this insight. Really, these tests shouldn't have mentioned `Scraper` at all. We've corrected that and done some version updates.
