### ISSUE TITLE
connecting to browser ide

### ISSUE THREAD

**Issue by swarbrick85** [learn-co-curriculum/oo-student-scraper#76]
all night (your time) it's been working. No i can't connect to ide for 30 minutes straight. Things like this have been happening for about a week now

**Comment by sgharms** [comment]
Hi there! This request sounds like an improvement to the Learn platform.

Please send your details to: support@learn.co.

[Raising issues on GitHub][raise] should be reserved for problems with
the curriculum itself (doesn't work, throws a Ruby error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
