### ISSUE TITLE
Suggestions for Improvement - Student Scraper

### ISSUE THREAD

**Issue by merecka** [learn-co-curriculum/oo-student-scraper#78]
As someone who is pretty much brand new to coding, I found getting started on this lab fairly difficult.  The main thing that I had a big challenge with was the CSS selectors.  I did not have a good understanding of how to select different attributes, classes, etc using the CSS selectors and even after reading the Learn.co labs covering this I still felt lost.  I eventually had to result to asking a technical coach for assistance and once they walked me through a couple of the attributes from the lab, I finally sort of got the hang of it.  

I think adding some more hints and/or examples of CSS selectors would make this lab much more manageable to someone with little to no experience with HTML/CSS like myself.  I don't really feel that the biggest learning point of this lab is trying to teach yourself CSS selectors (I assume that's covered in another part of the course).  But I feel like I spent a considerable amount of time struggling with it and it could have been a lot easier if there had been a bit more guidance.  I think the main learning points from this lab are objects, classes, instances, and iterating through arrays & hashes.  While the CSS selector is important, the material covered prior to this lab doesn't give enough preparation for it (in my opinion).

**Comment by maxwellbenton** [comment]
Hi @merecka,

Thank you for opening this issue. We've updated this lesson's instruction and incorporated changes based on your feedback, adding some additional guidance and a link to Nokogiri's reference materials on the use of the `.css` method, which should help prevent future students from experiencing the same challenges you faced. 

We apologize for any frustration you might have encountered, but thank you for contributing to this lesson.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
