### ISSUE TITLE
Tic-Tac-Toe with AI lab: Mystery red bar

### ISSUE THREAD

**Issue by theouternet** [learn-co-curriculum/oo-student-scraper#80]
Tic-Tac-Toe with AI lab:

I check off all steps of the "checklist", hit "submit", then a blank red bar is shown at the top of the screen:

https://imgur.com/oXSGkJM

The tests are passing. Readme is asking for a lot of things to be built on top of what's in spec; did my best without any guidance. Are there opaque requirements I'm not passing? What is this red bar, or what is keeping me from progressing, and what should I do next? Thanks.

**Comment by lizbur10** [comment]
Hi there,

Raising issues on GitHub should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via a quick edit, or bugs with the Learn platform (such as lights not turning green or IDE issues).

This issue would be perfect for the Ask a Question (AAQ) feature, where the Technical Coaches (on supported tracks) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out this helpful article in the Learn Help Center.

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
