### ISSUE TITLE
Executing code

### ISSUE THREAD

**Issue by pacosta613** [learn-co-curriculum/oo-student-scraper#9]
Even though my code passes all the tests, when I try "ruby bin/run" I get an error message. It doesn't execute the code. I asked for help and another student who submitted his project came across the same problem, even though he passes the tests.

**Comment by AnnJohn** [comment]
thanks @pacosta613. we'll look at this lab very soon and will get all the issues with it resolved.

**Comment by SophieDeBenedetto** [comment]
hi @pacosta613, this should be fixed now. thanks!
